#!/usr/bin/python
import os
import sys
from optparse import OptionParser

RABBITMQCTL = "/usr/sbin/rabbitmqctl"

parser = OptionParser()
parser.add_option("-w", "--warning", dest="warn", metavar="INT", type="int", default=100, help="Default: 100")
parser.add_option("-c", "--critical", dest="crit", metavar="INT", type="int", default=200, help="Default: 200")
parser.add_option("-v", "--vhost", dest="vhost", metavar="VIRTUAL_HOST", type="string", default="/", help="Default \"/\"")
(options, args) = parser.parse_args()

CRIT = int(options.crit)
WARN = int(options.warn)

COMMAND = "%s -q list_queues -p %s" % (RABBITMQCTL, options.vhost)

if not os.path.exists(RABBITMQCTL):
    sys.stdout.write("%s does not exist\n" % RABBITMQCTL)
    sys.exit(3)

if WARN > CRIT:
    sys.stdout.write(""Warning value cannot be greater than critical value\n")
    sys.exit(3)

data = os.popen(COMMAND).read().strip()

is_warn = False
is_crit = False
output = ""

for line in data.split("\n"):
    queue, length = line.split("\t")
    length = int(length)
    output += "%s = %s; " % (queue, length)
    if length > CRIT:
        is_crit = True
    if length > WARN:
        if is_crit is not True:
            is_warn = True

if is_crit is True:
    sys.stdout.write("CRITICAL - %s\n" % output)
    sys.exit(2)
if is_warn is True:
    sys.stdout.write("WARNING - %s\n" % output)
    sys.exit(1)

sys.stdout.write("OK - %s" % output)
sys.exit(0)

